name: Check Pullrequest

on:
  pull_request:
    types: [ edited, opened, labeled, unlabeled ]
    branches: [ "[1-9].*.*" ]

jobs:

  check_changelog:
    runs-on: ubuntu-latest
    steps:
      
      - name: check Changelog
        if: contains(github.event.pull_request.labels.*.name, 'release') && github.event.pull_request.body == ''
        run: exit 1
