name: Release

on:
  pull_request:
    types: [ closed ]
    branches: [ "[1-9].*.*" ]

jobs:

  publish:
    if: github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: PssbleTrngle/VersionManagment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        id: version

      - name: Update mod version
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: 'build.properties'
          property: 'mod_version'
          value: ${{ steps.version.outputs.next }}

      - name: Build Mod
        run: chmod +x ./gradlew && ./gradlew build

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Update Changelog
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: CHANGELOG.md
          contents: |
            .

            ## [${{ steps.version.outputs.next }}] - ${{ steps.date.outputs.date }}
            ${{ github.event.pull_request.body }}
          write-mode: append

      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v2
        with:
          token: ${{ secrets.CURSEFORGE_TOKEN }}
          project_id: 426334
          game_endpoint: minecraft
          file_path: build/libs/Floating-${{ steps.version.outputs.next }}.jar
          changelog: ${{ github.event.pull_request.body }}
          changelog_type: markdown
          display_name: Version ${{ steps.version.outputs.next }} (${{ github.ref }})
          game_versions: 8134,4458,7498
          release_type: ${{ steps.version.outputs.type }}

      - name: Create Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.next }}
          release_name: Release ${{ steps.version.outputs.next }}
          body: ${{ github.event.pull_request.body }}
          prerelease: ${{ steps.version.outputs.type == 'alpha' }}

      - name: Upload Mod Jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: build/libs/Floating-${{ steps.version.outputs.next }}.jar
          asset_name: floating.jar
          asset_content_type: application/java-archive

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v5
        with:
          message: Update Changelog
          add: build.properties CHANGELOG.md
          branch: ${{ github.ref }}
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}